# Generated by Django 5.1.1 on 2024-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_comment',
            field=models.ManyToManyField(blank=True, to='tbeapp.customer'),
        ),
    ]
