# Generated by Django 5.1.1 on 2024-10-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbeapp', '0003_product_customer_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
    ]
