# Generated by Django 5.1.1 on 2024-10-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeapp', '0007_alter_seller_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
