# Generated by Django 5.1.1 on 2024-10-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbeapp', '0009_product_owner_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tbeapp.seller'),
        ),
    ]
